name: Check Analyzer TOML

on:
  push:
    paths: 
      - 'analyzer.toml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: siddhant-deepsource/armory@main
